### ISSUE TITLE
Discussion about unsecure default resources in managed K8S Cluster that cause noise in response for automated process.

### ISSUE THREAD

**Issue by JnMik** [cyberark/KubiScan#13]
Hello again ! :)

When I run Kubiscan against an Amazon EKS cluster, I find a lot of HIGH and CRITICAL resources (mostly system:controller: stuff) that lives inside the cluster per default. (I supposed doing so on GKE or AKS would pretty much do the same).

I believe their extended privileges access is necessary for the cluster to work, so how should I interpret the response of Kubiscan regarding those resources.  Can we safely ignore them ? 
Should we add some knowledge about these resources in Kubiscan so they are not reported in the response  ? (Could be heavy in the code base and hard to maintain as kubernetes evolves quickly.. )

I'm trying to script an automated job that will use Kubiscan to detect unsafe resources, and notify me when new ones are detected. At the moment I filter the response with grep -v to avoid being notified for all the system:controller resources but I'm wondering if there would be a better approach.

Any idea ? 
How do you guys leverage this in your environments ? 

Cheers

**Comment by g3rzi** [comment]
Hey @JnMik !
Thanks again for reporting :)

This issue came up once.
It makes lots of noise because of the system's resources.

I added the "-lt <days>" flag that filters all the resources that are less than X days.
For example, when you run "kubiscan -rar" you will get lots of roles, some of them, like you wrote, are related to the system.
You will also notice for a volume that states when they were created (timestamp).
I thought, that because these roles were created in the beginning of the cluster creation they will have the oldest timestamp, so if you see that these default roles have time stamp of, let's say, 100 days, you can simply run:
`kubiscan -rar -lt 100`.
It will show you all the roles that exist less than 100 days.

I am not sure if this is the perfect solution, I can make some feature that won't show the default resources. Maybe this will be a better solution.

There is also the "-ns <namespace>" that will filter all the resources from specific namespace, for example:
`kubiscan -rar -ns default`

You can also filter by priority:
`kubiscan -rar -p high`
It will show you all the resources with "high" priority.

**Comment by JnMik** [comment]
Hey! :) 

So I played a bit with the -ns argument but find out it wasn't working with all resources. Roles or roles binding response was not affected by the filter. (Well I think hehe)

For the timestamp, I saw the option but with my infrastructure as code setup the difference between the eks managed resources and my pods are not that significant. So It's more or less applicable.

I don't really have a solution for the issue in mind, hardcoding all resources names to skip feels like a burden and a "not so clean way" to process lol

**Comment by g3rzi** [comment]
I thought that if there is a way to check when the cluster was exactly created, I can compare its timestamp to the resources and find the default one.

What command you ran with `-ns` that didn't work?
I didn't have issues with it.

**Comment by JnMik** [comment]
Hey buddy, sorry the delay I got off the hook for the weekend.

So I just ran a test to validate my point,
if I run this in the kubesican container:

`python3 /KubiScan/KubiScan.py -ho $KUBERNETES_ENDPOINT:$KUBERNETES_PORT -t /token -c /ca.crt -rs -ns kube-system`

You'll see resources in the the list that is not in kube-system namespace

Is that working for you ?
Cheers

**Comment by g3rzi** [comment]
The command you run should list you **only** the users from the `kube-system` namespace.

Yes, it works for me.
This is weird.
What about `python3 /KubiScan/KubiScan.py -ho $KUBERNETES_ENDPOINT:$KUBERNETES_PORT -t /token -c /ca.crt -rs -ns kube-system`, is it also doesn't show you the `kube-system` roles?

**Comment by JnMik** [comment]
That command
`python3 /KubiScan/KubiScan.py -ho $KUBERNETES_ENDPOINT:$KUBERNETES_PORT -t /token -c /ca.crt -rs -ns kube-system`
shows me ServiceAccount, Group and User from any namespace

**Comment by g3rzi** [comment]
Oh, sounds like a bug or something I didn't cover.

I will check.
Any change I do will be published only after 5.12.

**Comment by g3rzi** [comment]
We fixed the bug and added the feature for using namespace for other switches.
