### ISSUE TITLE
Insecured option

### ISSUE THREAD

**Issue by prasenforu** [cyberark/KubiScan#5]
Not an issue but insecure option should be added if only "TOKEN" is used.

otherwise every command run we will get following error ..

```
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

**Comment by g3rzi** [comment]
Thanks, I will check.
I added the insecure option by default but I had issues with that so I commented it: 
https://github.com/cyberark/KubiScan/blob/11de797015bb76750429d184fb4a3f543687d77b/engine/utils.py#L15

I think the problem was because I am using Kubernetes python client package and they didn't use this option. I will check if there is an option to fix it.
