### ISSUE TITLE
cannot run KubiScan

### ISSUE THREAD

**Issue by kamal2222ahmed** [cyberark/KubiScan#69]
## Summary
 Cannot run kubiscan -rr or any kubiscan command
*Provide brief overview and context for the discovered bug.*

## Steps to Reproduce
$kubiscan -rr
  File "/root/KubiScan/KubiScan.py", line 105
    match cve_severity:
          ^
SyntaxError: invalid syntax

**Comment by g3rzi** [comment]
Hi @kamal2222ahmed and @gmaran23 , sorry for the late response.
The current version of KubiScan is 1.6 (I still didn't release it yet) but from my checks it is stable and it worked for me.

I think you received the error because `match` is only supported by Python 3.10.  
What version of Python are you using? 

Anyway, I changed the code from `match` and `case` to `if else` so it should work for you now.  
Please check the latest current version from the GitHub page (version 1.6).
